### ISSUE TITLE
How to work with observable?

### ISSUE THREAD

**Issue by Morkoffka** [SamVerschueren/listr#87]
It's very likely that I'm doing something wrong, but when I try to run an example with Observable, I get this error
```
 ✖ Success

   → Observable is not defined
   Failure
{ ReferenceError: Observable is not defined
    at Task.task (/home/exeteres/gulp-project/test.js:6:9)
    at Promise.resolve.then.then.skipped (/home/exeteres/gulp-project/node_modules/listr/lib/task.js:168:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:705:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3 context: {} }
```

The code I am trying to run
```
const Listr = require('listr');
const tasks = new Listr([
{
    title: 'Success',
    task: () => {
        return new Observable(observer => {
            observer.next('Foo');

            setTimeout(() => {
                observer.next('Bar');
            }, 2000);

            setTimeout(() => {
                observer.complete();
            }, 4000);
        });
    }
},
{
    title: 'Failure',
    task: () => Promise.reject(new Error('Bar'))
}
]);
tasks.run().catch(err => {
    console.error(err);
});
```

**Comment by Morkoffka** [comment]
Sorry for disturbing.
I just installed the package `zen-observable`.
`const Observable = require('zen-observable');`

**Comment by SamVerschueren** [comment]
Yes, use whatever Observable package you want like zen or RxJS. Glad you got it working!

**Comment by Roms1383** [comment]
Sorry for re-posting on this, but there's something I can't get to understand : I can't find where `observer` variable comes from / is defined in your example.

**Comment by Roms1383** [comment]
Oh damn, by the `Observable` itself 😅
Sorry for polluting the messages thread 😓
